### ISSUE TITLE
Improve scanning speed on "More Info" page

### ISSUE THREAD

**Issue by leonyonz** [Cyrexxis/RokTracker#11]
**Is your feature request related to a problem? Please describe.**
It seems the "More Info" page scanning so slow than the original Nikolakis, it takes more time to finish if i want scan 500+ governor

**Describe the solution you'd like**
Idk, maybe decrease the delay /ms ?

**Comment by Cyrexxis** [comment]
I am not sure if it is the delay. Nikolakis uses his trained digits model for the more info page (also doesn't track rss gathered). Where I use tesseract for all OCR related things. I did that change because i noticed that the digits model had a couple of very consistent errors with some digits resulting in strange numbers when comparing scans. Something like -x million dead, for example.

But thanks for mentioning, I will try if it's possible to speed up that section a bit.

**Comment by quannv98k3** [comment]
Nikolakis just update his bot, when you release the new one?

**Comment by Cyrexxis** [comment]
This project is very different from the original for Nikolakis and doesn't need to get updated at the same time. But i tested a reduction of the wait time and currently it seems to work fine. I need to test it a bit more in the next week and will release it if it performs well. The improvement would be around 6 seconds per governor (from 24s to 18s average).

**Comment by leonyonz** [comment]
I think this ticket already solved with new updates #13 ,

tested on windows server 2019 work fine and not face slow issue in 'more info' page
