### ISSUE TITLE
[BUG] Incorrect ranking of the scan

### ISSUE THREAD

**Issue by BKamor** [Cyrexxis/RokTracker#72]
**Describe the bug**
Scans starts right in the middle. Instead of scanning the first three in ranking its starting with the fourth.

**To Reproduce**
1. Start scan
2. Check names (Excel with Ingame ranking)

**Expected behavior**
Scan from the beginning .

**Your Setup (please complete the following information):**
 - OS: Windows 11
 - Bluestacks Version: 5.13.215.1003
 - Android of Bluestacks: P64
 - Tracker Version: 4.0.1

**Comment by markm-io** [comment]
@BKamor are you sure you have the correct specs as outlined here

Display Tab ([Screenshot](https://github.com/Cyrexxis/RokTracker/blob/main/images/bluestacks-display.png))
Resolution: 1600x900
DPI: Custom (450)
Advanced Tab ([Screenshot](https://github.com/Cyrexxis/RokTracker/blob/main/images/bluestacks-advanced.png))
Android Debug Bride: Turned on

**Comment by Cyrexxis** [comment]
Like @markm-io said, to me, it also looks like an issue with the resolution or dpi.

**Comment by BKamor** [comment]
All options active, didn't change a thing when trying to scan

**Comment by morheus-rok** [comment]
Same problem. For 1600х900 display resolution, scans governors through one, besides it cannot do this automatically because it cannot close window of governor. With 1920x1080 resolution first problem is eliminated, but there is still a problem with closing window.
Scan cannot work with these settings

**Comment by Cyrexxis** [comment]
Hm, another reason why it starts with the 4th governor could be that "resume scan" is selected. And it is required that you use 1600x900 with 450 dpi, otherwise the positions the scanner uses are wrong. Also, you need to have the language in RoK set to English. Can you send me the resulting screenshots from the `temp_images` folder (feel free to blur personal info)? Maybe I find something wrong.
